language: go

go:
  - '1.9'
  - '1.10.x'
  - '1.x'
  - master

install:
  - go get github.com/mattn/goveralls

script:
  - go test -v  ./...
  - goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN
  - '[ -z "$(gofmt -s -l .)" ] || { gofmt -s -d -e . ; return 1; } '

matrix:
  allow_failures:
    - go: master
