[[constraint]]
  name = "github.com/nsqio/go-nsq"
  version = "1.0.7"

[[constraint]]
  name = "github.com/pierreprinetti/go-methodmux"
  version = "1.0.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
